### ISSUE TITLE
FPGA_FGV dependencies missing

### ISSUE THREAD

**Issue by brbrindle** [LabVIEW-DCAF/FPGAWaveform#1]
7/13 copy has project broken.

Both FPGA_FGV.vi and FPGA_FGV_action.ctl are missing as dependencies.

What are the base requirements for this.
I have:
Labview, RT and FPGA 2017
waveform library and DCAF libraries

**Comment by bkindinger** [comment]
Hey, thanks for taking a look at this.  This is my first time collaborating in DCAF and I didn't really expect to get feedback this early :).  You'll need LVRT/FPGA 2017 and "https://github.com/LabVIEW-Power-Electronic-Control/WaveformAcq".  Originally I was just going to use this for my Power Electronics applications, but maybe I misjudged other peoples desires.  The problem is that this will compete with the cRIO Waveform reference library which was something I wanted to avoid, but unlike that library this would allow for multiple acquisition engines.  I'm going to have to think harder on how I want to present it.  I guess what are you trying to do?  1 or N acquisition rates?  SAR or Delta Sigma modules?  Continuous of Finite?  Triggering?

**Comment by brbrindle** [comment]
first off thank you for your efforts, i know it takes a lot to put something out there

My first comment, If you are going to depend on something make that known. Secondly, might i suggest packaging your code with vipm. That way dependencies are known. I might suggest with all of its flaws, basing this module off of the NI waveform acquisition library instead of yours (btw... nice library of code you got there) or just package your dependencies in there with your module that way it works on a clean system.

So my intent is to simplify my waveform acquisition into DCAF. I did base my original code base on the NI example, using 1 acquisition rate across up to 20 channels. no SAF or Delta Sigma and Continuous needing no triggering. 

ultimately DCAF is attached to the waveform acquisition rather clumsily via CVT(low accuracy) and TDMS files (high accuracy) once everything is running. works, but not manageable for non RT experienced users.

EDIT... Closing this because its not really an issue consider two other issues recently posted would likely solve my gripe.

**Comment by bkindinger** [comment]
The LabVIEW-Power-Electronic-Control/WaveformAcq/ repo already has an vipm build.  You can try it if you like.  It just installs the code to LabVIEW 2017\vi.lib\NI\PowerElectronicsControl\WaveformAcq which up until this discussion was good enough for me.  There are no palettes yet, but there is an example project WaveformLibraryIFw.lvproj.  

The code is actually based on the NI Waveform Acquisition library, but I modified it to use the [Instruction Framework.](http://zone.ni.com/reference/en-XX/help/372614J-01/target5devicehelp/idl_instfwk_overview/).  The reason is that it enables me to have multiple acquisition engines in FPGA which is needed for my projects.  I'm gonna take some time talking to Jeff (owner of the Waveform AcquisitionLibrary) to see what the best way to resolve these conflicts would be.
